<#
.SYNOPSIS
    Deploys CIS service Proactive Remediations to Intune via Graph API.

.DESCRIPTION
    Creates Proactive Remediations (deviceHealthScripts) in Intune from detect/remediate
    PS1 pairs generated by split_cis_services.py. Detection runs every 8 hours — if a
    service is re-enabled, remediation fires automatically.

    Reads manifest.json and filters to service-* type entries.

    Run split_cis_services.py first to generate the output directory.

.PARAMETER Tenant
    Target tenant: QA or Prod. Resolves to utorontoqa.onmicrosoft.com or utoronto.onmicrosoft.com.

.PARAMETER ManifestFile
    Path to manifest.json. Deploys all service entries listed in the manifest.

.PARAMETER ConfigFile
    Path to cis-control-config.json for scope tag resolution.

.PARAMETER TestMode
    Deploy only the first service entry (for QA validation).

.EXAMPLE
    pwsh Deploy-CISServices.ps1 -Tenant QA -ManifestFile ./output/manifest.json -TestMode -WhatIf

.EXAMPLE
    pwsh Deploy-CISServices.ps1 -Tenant Prod -ManifestFile ./output/manifest.json
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)]
    [ValidateSet('QA', 'Prod')]
    [string]$Tenant,

    [string]$ManifestFile = "./output/manifest.json",

    [string]$ConfigFile = "./cis-control-config.json",

    [switch]$TestMode
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# 1. Load manifest and filter to service entries
# ---------------------------------------------------------------------------
if (-not (Test-Path $ManifestFile)) {
    Write-Error "Manifest not found: $ManifestFile. Run split_cis_services.py first."
    return
}

$manifestRaw = Get-Content $ManifestFile -Encoding UTF8 -Raw
if ($manifestRaw[0] -eq [char]0xFEFF) { $manifestRaw = $manifestRaw.Substring(1) }
$manifest = $manifestRaw | ConvertFrom-Json

$manifestDir = Split-Path $ManifestFile -Parent
$serviceEntries = @($manifest | Where-Object { $_.type -like 'service-*' })

if ($serviceEntries.Count -eq 0) {
    Write-Host "No service entries found in manifest." -ForegroundColor Yellow
    return
}

if ($TestMode) {
    $serviceEntries = @($serviceEntries[0])
    Write-Host "TestMode: deploying first entry only" -ForegroundColor DarkYellow
}

Write-Host "Loaded manifest: $($serviceEntries.Count) service entries" -ForegroundColor Gray

# ---------------------------------------------------------------------------
# 2. Load config for scope tags
# ---------------------------------------------------------------------------
if (-not (Test-Path $ConfigFile)) {
    Write-Error "Config not found: $ConfigFile"
    return
}

$configRaw = Get-Content $ConfigFile -Encoding UTF8 -Raw
if ($configRaw[0] -eq [char]0xFEFF) { $configRaw = $configRaw.Substring(1) }
$config = $configRaw | ConvertFrom-Json

# ---------------------------------------------------------------------------
# 3. Scope tag resolution cache
# ---------------------------------------------------------------------------
$scopeTagCache = @{}

function Resolve-ScopeTagId {
    param([string]$TagName)
    if ($TagName -eq '0' -or $TagName -eq 'Default') { return '0' }
    if ($scopeTagCache.ContainsKey($TagName)) { return $scopeTagCache[$TagName] }

    if ($WhatIfPreference) {
        $scopeTagCache[$TagName] = "WHATIF-$TagName"
        return "WHATIF-$TagName"
    }

    try {
        $uri = "https://graph.microsoft.com/beta/deviceManagement/roleScopeTags?`$filter=displayName eq '$TagName'"
        $response = Invoke-MgGraphRequest -Method GET -Uri $uri
        if ($response.value -and $response.value.Count -gt 0) {
            $id = $response.value[0].id.ToString()
            $scopeTagCache[$TagName] = $id
            Write-Host "  Resolved scope tag '$TagName' -> ID $id" -ForegroundColor Gray
            return $id
        }
    } catch {}

    Write-Warning "Scope tag '$TagName' not found. Using Default (0)."
    $scopeTagCache[$TagName] = '0'
    return '0'
}

# ---------------------------------------------------------------------------
# 4. Group resolution cache
# ---------------------------------------------------------------------------
$groupCache = @{}

function Resolve-GroupId {
    param([string]$GroupName)
    if ($groupCache.ContainsKey($GroupName)) { return $groupCache[$GroupName] }

    if ($WhatIfPreference) {
        $groupCache[$GroupName] = "WHATIF-$GroupName"
        return "WHATIF-$GroupName"
    }

    try {
        $encodedName = $GroupName -replace "'", "''"
        $uri = "https://graph.microsoft.com/v1.0/groups?`$filter=displayName eq '$encodedName'&`$select=id,displayName"
        $response = Invoke-MgGraphRequest -Method GET -Uri $uri
        if ($response.value -and $response.value.Count -gt 0) {
            $id = $response.value[0].id.ToString()
            $groupCache[$GroupName] = $id
            Write-Host "  Resolved group '$GroupName' -> ID $id" -ForegroundColor Gray
            return $id
        }
    } catch {}

    Write-Warning "Group '$GroupName' not found. Skipping assignment."
    return $null
}

# ---------------------------------------------------------------------------
# 5. Health script helpers
# ---------------------------------------------------------------------------
function Find-ExistingHealthScript {
    param([string]$DisplayName)
    if ($WhatIfPreference) { return $null }
    try {
        # $filter may not work on deviceHealthScripts — fetch all and match client-side
        $uri = "https://graph.microsoft.com/beta/deviceManagement/deviceHealthScripts?`$select=id,displayName"
        $all = @()
        do {
            $response = Invoke-MgGraphRequest -Method GET -Uri $uri
            $all += $response.value
            $uri = $response.'@odata.nextLink'
        } while ($uri)

        $match = $all | Where-Object { $_.displayName -eq $DisplayName }
        if ($match) { return $match }
    } catch {}
    return $null
}

function New-ProactiveRemediation {
    param(
        [object]$Entry,
        [string]$ScopeTagId,
        [string]$GroupId
    )

    # Build display name from detect script filename
    $detectFile = Split-Path $Entry.detectScript -Leaf
    $prName = $detectFile -replace ' - Detect\.ps1$', ''
    $result = @{ Name = $prName; Id = $null; Created = $false; Skipped = $false; Assigned = $false; Error = $null }

    if ($WhatIfPreference) {
        $assignMsg = if ($Entry.assignTo) { " (assign: $($Entry.assignTo))" } else { "" }
        Write-Host "  [WhatIf] Would create: $prName$assignMsg" -ForegroundColor DarkYellow
        $result.Id = 'WHATIF-ID'
        return $result
    }

    $existing = Find-ExistingHealthScript -DisplayName $prName
    if ($existing) {
        Write-Host "  SKIP (exists): $prName (ID: $($existing.id))" -ForegroundColor Yellow
        $result.Id = $existing.id; $result.Skipped = $true
        return $result
    }

    # Read and encode scripts
    $detectPath = Join-Path $manifestDir $Entry.detectScript
    $remediatePath = Join-Path $manifestDir $Entry.remediateScript
    $detectContent = Get-Content $detectPath -Encoding UTF8 -Raw
    $remediateContent = Get-Content $remediatePath -Encoding UTF8 -Raw

    $body = @{
        displayName              = $prName
        description              = "CIS service controls - generated by split_cis_services.py"
        detectionScriptContent   = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($detectContent))
        remediationScriptContent = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($remediateContent))
        runAsAccount             = "system"
        enforceSignatureCheck    = $false
        runAs32Bit               = $false
        roleScopeTagIds          = @($ScopeTagId)
        isGlobalScript           = $false
    }

    try {
        $response = Invoke-MgGraphRequest -Method POST `
            -Uri "https://graph.microsoft.com/beta/deviceManagement/deviceHealthScripts" `
            -Body ($body | ConvertTo-Json -Depth 10) `
            -ContentType "application/json"
        $result.Id = $response.id; $result.Created = $true
        Write-Host "  CREATED: $prName (ID: $($response.id))" -ForegroundColor Green
    } catch {
        $result.Error = $_.Exception.Message
        Write-Warning "Failed to create '$prName': $($_.Exception.Message)"
        return $result
    }

    # Assign to group with 8-hour schedule
    if ($GroupId -and $result.Id) {
        try {
            $assignBody = @{
                deviceHealthScriptAssignments = @(@{
                    target = @{
                        '@odata.type' = '#microsoft.graph.groupAssignmentTarget'
                        groupId       = $GroupId
                    }
                    runRemediationScript = $true
                    runSchedule = @{
                        '@odata.type' = '#microsoft.graph.deviceHealthScriptHourlySchedule'
                        interval      = 8
                    }
                })
            }
            Invoke-MgGraphRequest -Method POST `
                -Uri "https://graph.microsoft.com/beta/deviceManagement/deviceHealthScripts('$($result.Id)')/assign" `
                -Body ($assignBody | ConvertTo-Json -Depth 10) `
                -ContentType "application/json" | Out-Null
            $result.Assigned = $true
            Write-Host "  ASSIGNED: $prName -> $($Entry.assignTo) (8h schedule)" -ForegroundColor Green
        } catch {
            Write-Warning "Failed to assign '$prName': $($_.Exception.Message)"
            $result.Error = "Assignment failed: $($_.Exception.Message)"
        }
    }

    return $result
}

# ---------------------------------------------------------------------------
# 6. Connect to Graph
# ---------------------------------------------------------------------------
$tenantDomain = switch ($Tenant) {
    'QA'   { 'utorontoqa.onmicrosoft.com' }
    'Prod' { 'utoronto.onmicrosoft.com' }
}

if (-not $WhatIfPreference) {
    $requiredScopes = "DeviceManagementScripts.ReadWrite.All", "Group.Read.All"
    Disconnect-MgGraph -ErrorAction SilentlyContinue | Out-Null
    Write-Host "Connecting to Microsoft Graph ($Tenant`: $tenantDomain)..." -ForegroundColor White
    Connect-MgGraph -Scopes $requiredScopes -TenantId $tenantDomain -ContextScope Process -ErrorAction Stop
    Write-Host "Connected as $((Get-MgContext).Account) [$Tenant]" -ForegroundColor Green
} else {
    Write-Host "[WhatIf] Would connect to Microsoft Graph ($Tenant`: $tenantDomain)" -ForegroundColor DarkYellow
}

# ---------------------------------------------------------------------------
# 7. Confirmation
# ---------------------------------------------------------------------------
$assignGroups = @($serviceEntries | Where-Object { $_.assignTo } | ForEach-Object { $_.assignTo } | Select-Object -Unique)
Write-Host "`n=== Deployment Plan ===" -ForegroundColor White
Write-Host "  Tenant:       $Tenant ($tenantDomain)" -ForegroundColor White
Write-Host "  Remediations: $($serviceEntries.Count)" -ForegroundColor White
if ($assignGroups.Count -gt 0) {
    Write-Host "  Assign to:    $($assignGroups -join ', ')" -ForegroundColor Cyan
} else {
    Write-Host "  Assign to:    (none)" -ForegroundColor Gray
}

if (-not $WhatIfPreference) {
    $confirm = Read-Host "`nProceed? (y/N)"
    if ($confirm -ne 'y') {
        Write-Host "Aborted." -ForegroundColor Yellow
        return
    }
}

# ---------------------------------------------------------------------------
# 8. Deploy each service entry
# ---------------------------------------------------------------------------
$stats = @{ Created = 0; Skipped = 0; Failed = 0 }
$deploymentLog = [System.Collections.ArrayList]::new()

foreach ($entry in $serviceEntries) {
    # Resolve scope tag based on type
    $scopeTagName = switch ($entry.type) {
        'service-baseline'      { $config.scopeTags.readonly }
        'service-exceptionable' { $config.scopeTags.exceptionable }
        default                 { '0' }
    }
    $scopeTagId = Resolve-ScopeTagId -TagName $scopeTagName

    # Resolve group
    $groupId = $null
    if ($entry.assignTo) {
        $groupId = Resolve-GroupId -GroupName $entry.assignTo
    }

    $detectFile = Split-Path $entry.detectScript -Leaf
    $prName = $detectFile -replace ' - Detect\.ps1$', ''
    Write-Host "`n$prName" -ForegroundColor White

    $result = New-ProactiveRemediation -Entry $entry -ScopeTagId $scopeTagId -GroupId $groupId

    [void]$deploymentLog.Add([ordered]@{
        name = $result.Name; id = $result.Id
        detectScript = $entry.detectScript; remediateScript = $entry.remediateScript
        assignTo = $entry.assignTo; created = $result.Created
        skipped = $result.Skipped; assigned = $result.Assigned; error = $result.Error
    })

    if ($result.Created) { $stats.Created++ }
    if ($result.Skipped) { $stats.Skipped++ }
    if ($result.Error -and -not $result.Created) { $stats.Failed++ }
}

# ---------------------------------------------------------------------------
# 9. Write deployment log and summary
# ---------------------------------------------------------------------------
if (-not $WhatIfPreference -and $deploymentLog.Count -gt 0) {
    $deployedBy = try { (Get-MgContext).Account } catch { $env:USERNAME }
    $logContent = [ordered]@{
        deployedAt    = (Get-Date -Format 'o')
        deployedBy    = $deployedBy
        totalEntries  = $deploymentLog.Count
        created       = $stats.Created; skipped = $stats.Skipped; failed = $stats.Failed
        remediations  = @($deploymentLog)
    }
    $logDir = Split-Path $ManifestFile -Parent
    $logPath = Join-Path $logDir "deployment-log-services.json"
    $logJson = $logContent | ConvertTo-Json -Depth 10
    [System.IO.File]::WriteAllText(
        (Resolve-Path $logDir | Join-Path -ChildPath "deployment-log-services.json"),
        $logJson, [System.Text.UTF8Encoding]::new($false)
    )
    Write-Host "`nDeployment log: $logPath" -ForegroundColor Gray
}

Write-Host "`n=== Deployment Summary ===" -ForegroundColor White
Write-Host "  Created:    $($stats.Created)" -ForegroundColor Green
Write-Host "  Skipped:    $($stats.Skipped) (already exist)" -ForegroundColor Yellow
Write-Host "  Failed:     $($stats.Failed)" -ForegroundColor $(if ($stats.Failed -gt 0) { 'Red' } else { 'Gray' })
$assigned = @($deploymentLog | Where-Object { $_.assigned }).Count
Write-Host "  Assigned:   $assigned" -ForegroundColor $(if ($assigned -gt 0) { 'Cyan' } else { 'Gray' })
