#!/usr/bin/env python3
"""
split-cis-services.py

Reads CIS Build Kit System Service PowerShell scripts and a control decisions
config, then splits them into baseline and exceptionable service scripts.
Writes output PS1 files and manifest entries for the deployer.
"""

import argparse
import json
import re
from pathlib import Path


def parse_service_script(filepath: str) -> dict[str, str]:
    """Parse a CIS service PS1 script and extract the service hashtable.

    Returns:
        {display_name: registry_path, ...}
    """
    text = Path(filepath).read_text(encoding="utf-8-sig")

    services = {}
    # Match lines like:  'Service Name'   = 'HKLM:\...\ServiceKey'
    pattern = re.compile(r"'([^']+)'\s*=\s*'([^']+)'")
    # Only match inside the hashtable block
    in_hashtable = False
    for line in text.splitlines():
        stripped = line.strip()
        if re.match(r'\$\w+Services\s*=\s*@\{', stripped):
            in_hashtable = True
            continue
        if in_hashtable:
            if stripped == '}':
                break
            m = pattern.search(stripped)
            if m:
                services[m.group(1)] = m.group(2)

    return services


def _registry_key_to_svc_name(reg_path: str) -> str:
    """Extract the service short name from a registry path.

    'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\sshd' -> 'sshd'
    """
    return reg_path.rsplit("\\", 1)[-1]


def classify_services(
    services: dict[str, str],
    svc_controls: dict[str, dict],
) -> dict:
    """Classify services by disposition.

    Args:
        services: {display_name: registry_path} from the parsed script
        svc_controls: config serviceControls keyed by registry service name

    Returns:
        {
            "baseline": {display_name: registry_path},
            "exceptionable": [{"display_name", "registry_path", "cis_rec", "description"}, ...],
            "rejected": int,
        }
    """
    baseline = {}
    exceptionable = []
    rejected = 0

    for display_name, reg_path in services.items():
        svc_name = _registry_key_to_svc_name(reg_path)
        ctrl = svc_controls.get(svc_name)

        if not ctrl or ctrl.get("disposition") == "accept":
            baseline[display_name] = reg_path
        elif ctrl["disposition"] == "reject":
            rejected += 1
        elif ctrl["disposition"] == "exceptionable":
            exceptionable.append({
                "display_name": display_name,
                "registry_path": reg_path,
                "cis_rec": ctrl.get("cis_rec", ""),
                "description": ctrl.get("description", display_name),
            })

    return {
        "baseline": baseline,
        "exceptionable": exceptionable,
        "rejected": rejected,
    }


def generate_service_script(
    services: dict[str, str],
    level: str,
    title: str,
) -> str:
    """Generate a PowerShell service disable script.

    Args:
        services: {display_name: registry_path}
        level: "L1" or "L2"
        title: Script title for the header comment
    """
    # Build hashtable entries with aligned '='
    max_key_len = max((len(f"'{k}'") for k in services), default=0)
    entries = []
    for display_name, reg_path in sorted(services.items()):
        key = f"'{display_name}'"
        entries.append(f"    {key:<{max_key_len}} = '{reg_path}'")
    hashtable_body = "\n".join(entries)

    return f"""<#
    {title}
    Generated by split_cis_services.py
#>

#Requires -RunAsAdministrator

$Services = @{{
{hashtable_body}
}}

$DisabledCount = 0
$AlreadyDisabledCount = 0
$NotInstalledCount = 0

foreach ($service in $Services.GetEnumerator()) {{
    $ServiceName = $service.Key
    $ServicePath = $service.Value

    if (Test-Path -LiteralPath $ServicePath) {{
        $StartValue = (Get-ItemProperty -LiteralPath $ServicePath).Start

        if ($StartValue -and $StartValue -ne 4) {{
            Set-ItemProperty -LiteralPath $ServicePath -Name 'Start' -Value 4
            Write-Host "Disabled service $ServiceName." -ForegroundColor Yellow
            $DisabledCount++
        }} elseif ($StartValue -eq 4) {{
            Write-Host "Service $ServiceName is already disabled." -ForegroundColor Green
            $AlreadyDisabledCount++
        }}
    }} else {{
        Write-Host "Service $ServiceName is not installed." -ForegroundColor Green
        $NotInstalledCount++
    }}
}}

Write-Host "`nThis script configured $DisabledCount services as 'Disabled'." -ForegroundColor Cyan
Write-Host "$AlreadyDisabledCount services were already disabled and $NotInstalledCount are not installed." -ForegroundColor Green
"""


def _parse_level(filepath: str) -> str:
    """Parse level from script file path."""
    if "Level 1" in filepath or "L1" in filepath:
        return "L1"
    elif "Level 2" in filepath or "L2" in filepath:
        return "L2"
    return "L1"


def main(
    source_dir: str,
    config_path: str,
    output_dir: str = "./output",
) -> None:
    """Process service scripts and write output."""
    with open(config_path, encoding="utf-8-sig") as f:
        config = json.load(f)

    svc_controls = {
        k: v for k, v in config.get("serviceControls", {}).items()
        if not k.startswith("_")
    }

    # Find PS1 files
    source = Path(source_dir)
    ps1_files = sorted(source.rglob("*.ps1"))

    if not ps1_files:
        print(f"No PS1 files found in: {source_dir}")
        return

    print(f"Loaded config: {len(svc_controls)} service controls")
    print(f"Found {len(ps1_files)} PS1 file(s)")

    manifest = []
    out = Path(output_dir)

    for ps1 in ps1_files:
        level = _parse_level(str(ps1))
        services = parse_service_script(str(ps1))

        if not services:
            continue

        result = classify_services(services, svc_controls)

        # Write baseline
        if result["baseline"]:
            baseline_name = f"CIS {level} - Services"
            script = generate_service_script(
                result["baseline"], level, f"{baseline_name} — Baseline"
            )
            rel_path = f"baseline/{baseline_name}.ps1"
            full_path = out / rel_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(script, encoding="utf-8")

            manifest.append({
                "file": rel_path,
                "type": "baseline",
                "assignTo": "AllDevices",
            })

        # Write exceptionable scripts
        for ext in result["exceptionable"]:
            exc_name = f"CIS {ext['cis_rec']} - {ext['description']}"
            script = generate_service_script(
                {ext["display_name"]: ext["registry_path"]},
                level,
                f"{exc_name} — Exceptionable",
            )
            rel_path = f"exceptionable/{exc_name}.ps1"
            full_path = out / rel_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(script, encoding="utf-8")

            manifest.append({
                "file": rel_path,
                "type": "exceptionable",
                "assignTo": "AllDevices",
            })

        print(f"  {ps1.name}: {len(result['baseline'])} baseline, "
              f"{len(result['exceptionable'])} exceptionable, "
              f"{result['rejected']} rejected")

    # Write manifest
    manifest_path = out / "manifest.json"

    # Merge with existing manifest if present
    if manifest_path.exists():
        existing = json.loads(manifest_path.read_text(encoding="utf-8"))
        manifest = existing + manifest

    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    print(f"\nManifest written: {manifest_path} ({len(manifest)} total entries)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Split CIS System Service Scripts into baseline and exceptionable scripts."
    )
    parser.add_argument("--source", required=True, help="Directory containing CIS service PS1 scripts")
    parser.add_argument("--config", required=True, help="Path to cis-control-config.json")
    parser.add_argument("--output", default="./output", help="Output directory (default: ./output)")
    args = parser.parse_args()

    main(source_dir=args.source, config_path=args.config, output_dir=args.output)
